### ISSUE TITLE
Way too many sites visited on the first run

### ISSUE THREAD

**Issue by tredondo** [UChicagoSUPERgroup/TrackingTransparencyCCS2019#1]
Thank you for this project!

1. `git clone`, cd
2. `npm install && npm build`
3. `npm run start:chromium`
4. Navigate to TechChrunch.com
5. Click article
6. Click another link from article. For example I ended up at https://techcrunch.com/2020/07/21/tracking-the-growth-of-low-code-no-code-startups/
7. Click the extension

![image](https://user-images.githubusercontent.com/10043369/91000261-9adbf300-e57d-11ea-9a82-1094d5461c61.png)

I only visited 3 pages, not 1006.

The extension dashboard shows some sites I never visited:

![image](https://user-images.githubusercontent.com/10043369/91000351-d4146300-e57d-11ea-8c6d-e3769996f2d1.png)

Is it seeded with some data?

**Comment by weinshel** [comment]
When you run through `npm run start:chromium`, the test script seeds some sample data in so it is easier to view what the dashboard should look like. You can see this code in https://github.com/UChicagoSUPERgroup/TrackingTransparencyCCS2019/blob/master/test/chromium.js.

Installing the compiled extension directly in Chrome or Firefox will not result in any sample data being loaded.
